[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
fastReruns = true
magicEnabled = true

[client]
toolbarMode = "minimal"
showErrorDetails = true

[global]
developmentMode = false
disableWatchdogWarning = true

[logger]
level = "info"
messageFormat = "%(asctime)s - %(message)s"

[cache]
ttl = 3600
maxEntrySize = 50 